import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const script=readFileSync(new URL('../src/main.js',import.meta.url),'utf8').replace("import './style.css';",'').replace("import('./scene.js')","Promise.reject(new Error('WebGL unavailable'))");
function setup(reduced=false){const dom=new JSDOM(html,{url:'https://kindermanbarros.github.io',runScripts:'outside-only'});let observer;dom.window.matchMedia=()=>({matches:reduced,addEventListener(){}});dom.window.IntersectionObserver=class{constructor(callback){observer=callback}observe(){}disconnect(){}};dom.window.eval(script);return{dom,document:dom.window.document,observer:()=>observer([{isIntersecting:true}])}}
test('resume and project remain available without JavaScript',()=>{const dom=new JSDOM(html);const d=dom.window.document;assert.match(d.querySelector('h1').textContent,/Engenharia/);assert.match(d.querySelector('#project-title').textContent,/Iontech/);assert.equal(d.querySelectorAll('.job').length,6);assert.equal(d.documentElement.lang,'pt-BR');for(const a of d.querySelectorAll('a[href^="#"]')){const id=a.getAttribute('href').slice(1);if(id)assert.ok(d.getElementById(id),id)}assert.ok(existsSync(new URL('../public/assets/kinderman-resume.pdf',import.meta.url)));assert.equal(readFileSync(new URL('../public/assets/kinderman-resume.pdf',import.meta.url)).subarray(0,4).toString(),'%PDF');dom.window.close()});
test('3D selectors update project details and accessible tabs',()=>{const {dom,document:d}=setup();d.querySelector('.object-choice[data-project=sdo]').click();assert.equal(d.querySelector('#project-title').textContent,'SDO Companion');assert.match(d.querySelector('#project-description').textContent,/sincronizados/);assert.equal(d.querySelector('#tab-sdo').getAttribute('aria-selected'),'true');assert.equal(d.querySelector('#project-panel').getAttribute('aria-labelledby'),'tab-sdo');assert.equal(d.querySelector('#project-link').target,'_blank');d.querySelector('.object-choice[data-project=xr]').click();assert.equal(d.querySelector('#project-link').getAttribute('href'),'#trajetoria');assert.equal(d.querySelector('#project-link').hasAttribute('target'),false);assert.equal(d.querySelectorAll('[role=tab][aria-selected=true]').length,1);dom.window.close()});
test('keyboard tabs wrap and support Home and End',()=>{const {dom,document:d}=setup();const key=(id,k)=>d.querySelector(id).dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:k,bubbles:true}));key('#tab-iontech','ArrowLeft');assert.equal(d.activeElement.id,'tab-xr');key('#tab-xr','Home');assert.equal(d.activeElement.id,'tab-iontech');key('#tab-iontech','End');assert.equal(d.activeElement.id,'tab-xr');key('#tab-xr','ArrowRight');assert.equal(d.activeElement.id,'tab-iontech');dom.window.close()});
test('reduced motion starts paused and can be toggled',()=>{const {dom,document:d}=setup(true);const b=d.querySelector('#motion-toggle');assert.equal(b.getAttribute('aria-pressed'),'true');assert.equal(b.textContent,'Ativar movimento');b.click();assert.equal(b.getAttribute('aria-pressed'),'false');dom.window.close()});
test('WebGL loading failure keeps project interactions available',async()=>{const {dom,document:d,observer}=setup();await observer();assert.equal(d.querySelector('#motion-toggle').hidden,true);assert.match(d.querySelector('.scene-instructions>span').textContent,/botões/);d.querySelector('#tab-sdo').click();assert.equal(d.querySelector('#project-title').textContent,'SDO Companion');dom.window.close()});
