import './style.css';
const projects={
 iontech:{title:'Iontech Serviços Hospitalares',category:'WEB / PROJETO PROFISSIONAL',description:'Um ponto de encontro entre a empresa e seus clientes. Desenvolvimento e manutenção do site institucional da Iontech, parte da minha atuação com software e infraestrutura na empresa.',facts:[['Contexto','Software Developer na Iontech · 2020–2021'],['Contribuição','Desenvolvimento e manutenção do site institucional.']],tags:['Website institucional','Desenvolvimento web','Manutenção'],url:'https://iontechmanaus.com.br',link:'Visitar site',art:'<div class="browser-visual"><div class="browser-top">● ● ●</div><div class="ion-content"><div class="ion-logo">IONTECH</div><div class="ion-columns"><div><h4>Tecnologia a serviço do cuidado.</h4><p>Serviços hospitalares · Manaus</p></div><div class="ion-geometry">+</div></div></div></div><span class="project-label">REPRESENTAÇÃO CONCEITUAL DO PROJETO · NÃO É CAPTURA DO SITE</span>'},
 sdo:{title:'SDO Companion',category:'ANDROID / PROJETO AUTORAL',description:'A mesa de RPG, sempre à mão. Um companion para Silêncio dos Oráculos que reúne fichas, campanhas, regras e operações de sessão. Os dados são gravados localmente e sincronizados quando há conexão.',facts:[['Problema','Fichas, anotações e controles de sessão espalhados.'],['Solução','Persistência offline, sincronização Firebase e resolução de conflitos por campo.'],['Status','Em desenvolvimento ativo.']],tags:['Kotlin','Jetpack Compose','Room','Firebase','Clean Architecture'],url:'https://github.com/KindermanBarros/sdo-companion',link:'Explorar repositório',art:'<div class="phone-visual"><div class="phone-notch"></div><div class="phone-tabs"><span>FICHA</span><span>CAMPANHA</span><span>SESSÃO</span></div><h4>Silêncio dos<br>Oráculos</h4><p>Seu personagem.<br>Sua próxima história.</p><div class="phone-bar"></div><div class="phone-bars"><div class="phone-stat">12<small>VIGOR</small></div><div class="phone-stat">08<small>AGILIDADE</small></div><div class="phone-stat">10<small>MENTE</small></div><div class="phone-stat">06<small>PRESENÇA</small></div></div></div><span class="project-label">REPRESENTAÇÃO CONCEITUAL · DADOS ILUSTRATIVOS</span>'},
 xr:{title:'Além da interface plana',category:'ANDROID XR / EXPERIÊNCIA PROFISSIONAL',description:'Experiências imersivas e provas de conceito para plataformas emergentes. No SIDIA, trabalho com Android XR, computação espacial, wearables e novas formas de interação entre pessoas e dispositivos.',facts:[['Atuação','Mobile XR e engenharia Android no SIDIA · 2025–atual'],['Foco','Interação espacial, integração com hardware e desempenho.'],['Apresentação','Área de atuação profissional; sem exposição de projetos internos.']],tags:['Android XR','Unity','C#','OpenXR','Compose for XR'],url:'#trajetoria',link:'Ver experiência',art:'<span class="xr-caption">COMPUTAÇÃO ESPACIAL</span><div class="xr-visual"><i></i><i></i></div><span class="project-label">OBJETO CONCEITUAL · EXPERIÊNCIA PROFISSIONAL</span>'}
};
let active='iontech';let scene;let paused=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function selectProject(id){if(!projects[id])return;active=id;const p=projects[id];document.querySelector('#project-title').textContent=p.title;document.querySelector('#project-category').textContent=p.category;document.querySelector('#project-description').textContent=p.description;document.querySelector('#project-art').innerHTML=p.art;document.querySelector('#project-facts').replaceChildren(...p.facts.flatMap(([label,value])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;return[dt,dd]}));document.querySelector('#project-tags').replaceChildren(...p.tags.map(tag=>{const el=document.createElement('span');el.textContent=tag;return el}));const link=document.querySelector('#project-link');link.href=p.url;link.innerHTML=p.link+' <span>↗</span>';if(p.url.startsWith('#')){link.removeAttribute('target');link.removeAttribute('rel')}else{link.target='_blank';link.rel='noopener noreferrer'}document.querySelector('#project-panel').setAttribute('aria-labelledby','tab-'+id);document.querySelectorAll('[data-project]').forEach(btn=>{const selected=btn.dataset.project===id;if(btn.getAttribute('role')==='tab'){btn.setAttribute('aria-selected',String(selected));btn.tabIndex=selected?0:-1}else{btn.setAttribute('aria-pressed',String(selected));btn.classList.toggle('active',selected)}});document.querySelector('.exhibit-number').textContent='0'+(Object.keys(projects).indexOf(id)+1)+' — 03';document.querySelector('#scene-status').textContent=p.title+' selecionado';scene?.select(id)}
document.querySelectorAll('[data-project]').forEach(btn=>btn.addEventListener('click',()=>selectProject(btn.dataset.project)));
const tabs=[...document.querySelectorAll('[role=tab]')];tabs.forEach((tab,i)=>tab.addEventListener('keydown',event=>{let index;if(event.key==='ArrowRight')index=(i+1)%tabs.length;else if(event.key==='ArrowLeft')index=(i+tabs.length-1)%tabs.length;else if(event.key==='Home')index=0;else if(event.key==='End')index=tabs.length-1;else return;event.preventDefault();tabs[index].focus();selectProject(tabs[index].dataset.project)}));
const motion=document.querySelector('#motion-toggle');function setPaused(value){paused=value;motion.setAttribute('aria-pressed',String(paused));motion.textContent=paused?'Ativar movimento':'Pausar movimento';scene?.pause(paused)}motion.addEventListener('click',()=>setPaused(!paused));window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>setPaused(e.matches));setPaused(paused);selectProject(active);
// Core content is available before WebGL or its optional module loads.
const host=document.querySelector('#scene');const observer=new IntersectionObserver(async entries=>{if(!entries.some(e=>e.isIntersecting))return;observer.disconnect();try{const {createStudio}=await import('./scene.js');scene=createStudio(host,selectProject,paused);scene.select(active)}catch{document.querySelector('.scene-instructions>span').textContent='Explore os projetos pelos botões abaixo';motion.hidden=true;host.setAttribute('aria-label','Apresentação dos projetos sem animação 3D')}},{rootMargin:'150px'});observer.observe(host);
