import * as THREE from 'three';
export function createStudio(host,onSelect,initiallyPaused){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.setClearColor(0x100f12,0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(renderer.domElement);host.classList.add('scene-ready');
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(6.3,6,9.6);camera.lookAt(0,.5,0);
 scene.add(new THREE.AmbientLight(0xe5cddd,1.6));const key=new THREE.DirectionalLight(0xf0d3ac,3);key.position.set(2,6,4);scene.add(key);const rim=new THREE.PointLight(0xc14165,35,18);rim.position.set(-4,3,-2);scene.add(rim);
 const world=new THREE.Group();scene.add(world);const metal=new THREE.MeshStandardMaterial({color:0x46333e,metalness:.75,roughness:.33});const dark=new THREE.MeshStandardMaterial({color:0x1b1821,metalness:.65,roughness:.35});const gold=new THREE.MeshStandardMaterial({color:0xb39a78,metalness:.78,roughness:.3});
 function box(w,h,d,material,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);m.position.set(x,y,z);return m}
 const plinth=new THREE.Mesh(new THREE.CylinderGeometry(3.55,3.65,.25,80),new THREE.MeshStandardMaterial({color:0x211923,metalness:.2,roughness:.75}));plinth.position.y=-.6;world.add(plinth);const ring=new THREE.Mesh(new THREE.TorusGeometry(3.5,.015,8,90),gold);ring.rotation.x=Math.PI/2;ring.position.y=-.465;world.add(ring);
 const objects={};const hitTargets=[];
 function register(id,group){group.userData.project=id;group.traverse(o=>{if(o.isMesh){o.userData.project=id;hitTargets.push(o)}});objects[id]=group;world.add(group)}
 function screenTexture(){const c=document.createElement('canvas');c.width=768;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#162425';ctx.fillRect(0,0,768,512);ctx.fillStyle='#d9ddd5';ctx.font='60px Georgia';ctx.fillText('Iontech',50,235);ctx.font='24px sans-serif';ctx.fillText('iontechmanaus.com.br',50,290);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
 const laptop=new THREE.Group();laptop.position.set(-1.15,-.35,-.7);laptop.rotation.y=.25;laptop.add(box(2.65,.12,1.75,metal,0,0,.25));const lid=new THREE.Group();lid.position.set(0,.94,-.58);lid.rotation.x=-.13;lid.add(box(2.65,1.8,.13,dark));const display=new THREE.Mesh(new THREE.PlaneGeometry(2.4,1.56),new THREE.MeshBasicMaterial({map:screenTexture('iontech')}));display.position.z=.071;lid.add(display);laptop.add(lid);for(let r=0;r<4;r++)for(let c=0;c<10;c++)laptop.add(box(.18,.014,.12,dark,-1.05+c*.23,.075,-.05+r*.19));laptop.add(box(.75,.016,.3,dark,0,.08,.8));register('iontech',laptop);
 const phone=new THREE.Group();phone.position.set(1.15,.55,.8);phone.rotation.set(-.25,-.45,.12);phone.add(box(1.02,1.97,.14,metal));const phoneScreen=new THREE.Mesh(new THREE.PlaneGeometry(.91,1.76),new THREE.MeshBasicMaterial({map:new THREE.TextureLoader().load('/assets/projects/sdo-dashboard.jpg',texture=>{texture.colorSpace=THREE.SRGBColorSpace;request()})}));phoneScreen.position.z=.075;phone.add(phoneScreen);phone.add(box(.32,.04,.01,dark,0,.89,.088));register('sdo',phone);
 const xr=new THREE.Group();xr.position.set(.85,.05,-1.65);xr.rotation.y=-.35;const glassMaterial=new THREE.MeshPhysicalMaterial({color:0x492737,metalness:.2,roughness:.17,transparent:true,opacity:.72,clearcoat:1});for(const x of[-.48,.48]){const lens=new THREE.Mesh(new THREE.SphereGeometry(.48,24,16),glassMaterial);lens.scale.set(1,.72,.18);lens.position.x=x;xr.add(lens);const frame=new THREE.Mesh(new THREE.TorusGeometry(.47,.026,8,36),gold);frame.scale.y=.72;frame.position.x=x;xr.add(frame)}xr.add(box(.18,.04,.07,gold));for(const x of[-.94,.94])xr.add(box(.045,.045,.9,metal,x,.13,-.4));register('xr',xr);
 let active='iontech',paused=initiallyPaused,visible=true,drag=false,moved=false,lastX=0,lastY=0,startX=0,startY=0,yaw=0,pitch=0,raf=0;const raycaster=new THREE.Raycaster();const pointer=new THREE.Vector2();let mobile=false;const basePositions=Object.fromEntries(Object.entries(objects).map(([id,g])=>[id,g.position.clone()]));const baseY=Object.fromEntries(Object.entries(objects).map(([id,g])=>[id,g.position.y]));
 function render(time=0){raf=0;if(!visible||document.hidden)return;world.rotation.y+=(yaw-world.rotation.y)*.09;world.rotation.x+=(pitch-world.rotation.x)*.09;for(const[id,g]of Object.entries(objects)){const desired=baseY[id]+(id===active?.18:0)+(!paused?Math.sin(time*.0006+baseY[id])* .025:0);g.position.y+=(desired-g.position.y)*.12}renderer.render(scene,camera);if(!paused||drag||Math.abs(yaw-world.rotation.y)>.001||Math.abs(pitch-world.rotation.x)>.001||Object.entries(objects).some(([id,g])=>Math.abs(g.position.y-baseY[id]-(id===active?.18:0))>.002))raf=requestAnimationFrame(render)}
 function request(){if(!raf&&visible&&!document.hidden)raf=requestAnimationFrame(render)}
 function arrange(){for(const[id,g]of Object.entries(objects)){g.visible=!mobile||id===active;g.position.x=mobile?0:basePositions[id].x;g.position.z=mobile?0:basePositions[id].z;}request()}
 function pick(event){const b=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-b.left)/b.width*2-1,-(event.clientY-b.top)/b.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(hitTargets.filter(o=>objects[o.userData.project].visible),false)[0]?.object.userData.project}
 host.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag=true;moved=false;lastX=startX=e.clientX;lastY=startY=e.clientY;host.setPointerCapture(e.pointerId);request()});host.addEventListener('pointermove',e=>{if(!drag){host.style.cursor=pick(e)?'pointer':'grab';return}const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.hypot(e.clientX-startX,e.clientY-startY)>8)moved=true;yaw=THREE.MathUtils.clamp(yaw+dx*.004,-.7,.7);pitch=THREE.MathUtils.clamp(pitch+dy*.002,-.1,.18);lastX=e.clientX;lastY=e.clientY;request()});host.addEventListener('pointerup',e=>{if(!drag)return;drag=false;if(!moved){const id=pick(e);if(id)onSelect(id)}request()});host.addEventListener('pointerleave',()=>{drag=false});host.addEventListener('pointercancel',()=>{drag=false});
 const resize=new ResizeObserver(()=>{const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;mobile=width<600;camera.position.set(mobile?2.4:6.3,mobile?2.8:6,mobile?7.8:9.6);camera.lookAt(0,.5,0);arrange();camera.updateProjectionMatrix();request()});resize.observe(host);
 const visibility=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)request();else if(raf){cancelAnimationFrame(raf);raf=0}});visibility.observe(host);document.addEventListener('visibilitychange',()=>{if(document.hidden&&raf){cancelAnimationFrame(raf);raf=0}else request()});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();host.classList.remove('scene-ready');renderer.domElement.style.display='none'});renderer.domElement.addEventListener('webglcontextrestored',()=>{host.classList.add('scene-ready');renderer.domElement.style.display='';request()});request();return{select(id){active=id;arrange()},pause(value){paused=value;request()}};
}
